title: Lavkush Gupta
position: Data Science | Machine Learning | Data Analysis
affiliation: Portfolio
email: lavkushgupt@live.in
keywords: data science portfolio
#google_scholar: https://scholar.google.com/
github_link: https://github.com/llavkush
linkedin: https://www.linkedin.com/in/lavkushsg/
avatar: ./assets/img/avatar.png
google_analytics: #UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
#description:
#canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
